export const ALL_COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Cook Islands',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'Gabon',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'North Korea',
  'Northern Mariana',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'The Bahamas',
  'The Gambia',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'US Virgin Islands',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
] as const;

export const SUPPORTED_COUNTRIES = [
  'Albania',
  'Algeria',
  'Angola',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Belgium',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brunei',
  'Bulgaria',
  'Cambodia',
  'Canada',
  'Chile',
  'Colombia',
  'Costa Rica',
  "Cote d'Ivoire",
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Estonia',
  'Ethiopia',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Guyana',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Laos',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao SAR China',
  'Madagascar',
  'Malaysia',
  'Malta',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Netherlands',
  'New Zealand',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Panama',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Rwanda',
  'San Marino',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'St. Lucia',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Tanzania',
  'Thailand',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan'
] as const;

export const PRIMARY_TAGS = [
  'Accessories',
  'Accounting',
  'Admin',
  'Agency',
  'Agriculture',
  'App',
  'Architecture',
  'Artist',
  'Attorney',
  'Automotive',
  'Band',
  'Bank',
  'Bar',
  'Barber',
  'Beauty',
  'Beauty & Wellness',
  'Blog',
  'Book',
  'Business',
  'Cafe',
  'Cars',
  'Charity',
  'Church',
  'Coaching',
  'Coffee Shop',
  'College',
  'Coming Soon',
  'Conference',
  'Construction',
  'Consulting',
  'Corporate',
  'Countdown',
  'Creative',
  'CV',
  'Dance',
  'Dashboard',
  'Delivery',
  'Dentist',
  'Design',
  'Designer',
  'Directory',
  'DJ',
  'Doctor',
  'Documentation',
  'Donation',
  'Education',
  'Entertainment',
  'Error',
  'Event',
  'Farm',
  'Fashion',
  'Film',
  'Finance',
  'Fitness',
  'Florist',
  'Food',
  'Food & Drink',
  'Furniture',
  'Game',
  'Guesthouse',
  'Gym',
  'Health',
  'Help center',
  'Homeware',
  'Hospital',
  'Hostel',
  'Hotel',
  'Inn',
  'Insurance',
  'Interior design',
  'Investment',
  'IT company',
  'Jewelry',
  'Job Portal',
  'Kids',
  'Landing page',
  'Law Firm',
  'Learning',
  'Lifestyle',
  'Logistics',
  'Magazine',
  'Marketing',
  'Marketplace',
  'Massage',
  'Medical',
  'Mobile',
  'Movie',
  'Multi Layout',
  'Music',
  'Musician',
  'News',
  'Newsletter',
  'Newspaper',
  'Nonprofit',
  'One Page',
  'Other',
  'Personal',
  'Pets',
  'Photography',
  'Photography & Video',
  'Podcast',
  'Political',
  'Portfolio',
  'Profile',
  'Radio',
  'Real Estate',
  'Recipe',
  'Recruitment',
  'Religion',
  'Restaurant',
  'Resume',
  'Retail',
  'SaaS',
  'Salon',
  'School',
  'Shop',
  'Small Business',
  'Soccer',
  'Social',
  'Software',
  'Spa',
  'Sports',
  'Startup',
  'Support',
  'Technology',
  'Therapy',
  'Tourism',
  'Transport',
  'Travel',
  'UI Kit',
  'Under Construction',
  'University',
  'Veterinary',
  'Video',
  'Wedding',
  'Wellness',
  'Winery'
] as const;

export const FORBIDDEN_CATEGORY_NAMES = [
  'Advocacy & Campaigns',
  'Agency',
  'Agriculture',
  'App',
  'Architecture',
  'Architecture & Design',
  'Art & Design Blog',
  'Arts & Crafts Store',
  'Bakery',
  'Banking & Investment',
  'Bar & Nightclub',
  'Beauty & Wellness Store',
  'Blog & Editorial',
  'Blockchain, Cryptocurrency & NFTs',
  'Book',
  'Books & Publishers Store',
  'Business & Finance Blog',
  'Cafe & Coffee Shop',
  'Cars',
  'Catering & Delivery',
  'Charity & Fundraising',
  'Chiropractor & Physiotherapist',
  'Classes & Courses',
  'Cleaning',
  'Clinic & Pharmacy',
  'College / University',
  'Coming Soon',
  'Community & Non-Profits',
  'Construction & Home Services',
  'Consulting & Coaching',
  'Creative Agency',
  'Creators & Influencers',
  'Culture, Performance & Entertainment',
  'Dance',
  'Dentist',
  'Design Portfolio',
  'Digital Products Store',
  'Documentation',
  'Documentation & Help Center',
  'Doctor',
  'Early Education',
  'Education',
  'Electronics Store',
  'Environment',
  'Event Production',
  'Events',
  'Events, Conferences & Meetups',
  'Fashion & Clothing Store',
  'Film & TV',
  'Finance & Accounting',
  'Fitness & Gym',
  'Florist & Plants Store',
  'Food & Drink',
  'Food & Drinks Store',
  'Food & Recipe Blog',
  'Foundations & NGO',
  'Freelancers & Consultants',
  'Furniture',
  'Gallery & Museum',
  'Gaming',
  'Government & Political',
  'Hair & Beauty',
  'Health & Nutrition',
  'Health & Wellness',
  'Home Construction',
  'Home Decor Store',
  'Home Services & Maintenance',
  'Hospital',
  'Hotels & Lodging',
  'HR & Recruiting',
  'Insurance',
  'Interior Design',
  'Jewelry & Accessories Store',
  'Job Portal',
  'Kids & Babies Store',
  'Landing',
  'Landscaping & Gardening',
  'Law Firm & Attorney',
  'Lifestyle Blog',
  'Magazine',
  'Makeup & Cosmetics',
  'Marketing & Advertising',
  'Medical',
  'Mobile App',
  'Music & Audio',
  'Music Events & Festivals',
  'Music Industry & Promotion',
  'Musicians & Bands',
  'Nature & Conservation',
  'News',
  'Newsletter',
  'Online Education',
  'Outdoor & Adventure',
  'Personal Blog',
  'Pets & Animals Store',
  'Photography & Video Portfolio',
  'Podcast & Radio',
  'Political',
  'Portfolio & Agency',
  'Product Launch / Coming Soon',
  'Professional Services',
  'Property Management & HOA',
  'Public services',
  'Real Estate',
  'Real Estate & Property Management',
  'Recruiting',
  'Religious & Spiritual',
  'Renewable energy',
  'Residential Design',
  'Restaurant',
  'Resume & Personal',
  'Resume & CV',
  'Retail & E-Commerce',
  'Salon & Barbershop',
  'Schools',
  'Software & SaaS',
  'Spa',
  'Sports',
  'Sports & Outdoors Store',
  'Startup',
  'Support/Help center',
  'Sustainability',
  'Tattoo',
  'Tech',
  'Technology',
  'Therapy & Psychology',
  'Tourism',
  'Transport',
  'Transportation & Automotive',
  'Travel & Hospitality',
  'Travel Blog',
  'UI Kit',
  'UI Kit & Landing Page Components',
  'Veterinary',
  'Volunteer & Community',
  'Vows',
  'Waitlist',
  'Weddings',
  'Weddings & Events',
  'Winery'
] as const;

export const SITE_TYPE_OPTIONS = [
  { id: 'static', label: 'Static pages' },
  { id: 'cms', label: 'CMS collections' },
  { id: 'ecommerce', label: 'Ecommerce' },
  { id: 'multi-layout', label: 'Multi layout' }
] as const;

export const FEATURE_OPTIONS = [
  { id: 'gsap', label: 'GSAP animations' },
  { id: 'cms', label: 'CMS' },
  { id: 'ecommerce', label: 'Ecommerce' },
  { id: 'interactions', label: 'Advanced interactions' },
  { id: 'components', label: 'Reusable components' },
  { id: 'memberships', label: 'Memberships' },
  { id: 'localization', label: 'Localization' },
  { id: 'dark-mode', label: 'Dark mode' }
] as const;

function normalizeCountryToken(value: string): string {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\*/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/gi, ' ')
    .trim()
    .toLowerCase();
}

const COUNTRY_ALIASES = new Map<string, string>([
  ['antigua and barbuda', 'antigua & barbuda'],
  ['saint lucia', 'st. lucia'],
  ['trinidad and tobago', 'trinidad & tobago'],
  ['macau', 'macao sar china'],
  ['macedonia', 'north macedonia'],
  ['the bahamas', 'bahamas'],
  ['the gambia', 'gambia']
]);

const SUPPORTED_COUNTRY_TOKENS = new Set(
  SUPPORTED_COUNTRIES.map((value) => normalizeCountryToken(value))
);

export function isSupportedCountry(country: string): boolean {
  const normalized = normalizeCountryToken(country);
  if (!normalized) return false;

  const alias = COUNTRY_ALIASES.get(normalized);
  if (alias) {
    return SUPPORTED_COUNTRY_TOKENS.has(normalizeCountryToken(alias));
  }

  return SUPPORTED_COUNTRY_TOKENS.has(normalized);
}

export const CATEGORY_OPTIONS = [...FORBIDDEN_CATEGORY_NAMES].sort((left, right) =>
  left.localeCompare(right)
);
